### ISSUE TITLE
What should be the values for alpha and beta?

### ISSUE THREAD

**Issue by sneaker-rohit** [sneaker-rohit/PI2-ns-3#1]
PIE Linux Implementation makes use of alpha and beta values as 2 and 20 respectively. 

https://github.com/torvalds/linux/blob/687ee0ad4e897e29f4b41f7a20c866d74c5e0660/net/sched/sch_pie.c

PI2 Linux Implementation has 10 and 100.

https://github.com/olgabo/dualpi2/blob/master/sch_pi2/sch_pi2.c

PIE ns-3 has 0.125 and 1.25. What should be the values used for PI2-ns-3 Implementation? The common thing is the ratio between the values of alpha and beta.

**Comment by mohittahiliani** [comment]
Since there is no other implementation of PiSquare, we should follow its Linux implementation. So we should use 10 and 100, unless the paper says something else.

**Comment by sneaker-rohit** [comment]
Alright. I do not see the paper talking about any other values. I will keep 10 and 100 for now.
