### ISSUE TITLE
Changes in CalculateP () for PI2

### ISSUE THREAD

**Issue by sneaker-rohit** [sneaker-rohit/PI2-ns-3#3]
In PIE, the designers had introduced the scaling factors alpha and beta which increase as the drop/mark probability increases. PI2 removes the scaling part. 

http://code.nsnam.org/ns-3.26/file/af21cf79d193/src/traffic-control/model/pie-queue-disc.cc

Therefore line no. 314 through 341 needs to be commented.

In PIE, we tune the drop probability to increase quickly when delay > 200ms. PI2 comments that part.

Therefore line no. 352 to 355 would be commented. 

Also, 368 to 372 needs to be commented.

**Comment by mohittahiliani** [comment]
I would suggest to remove those lines instead of commenting.

**Comment by sneaker-rohit** [comment]
I have some doubts in the function calculating the probability. I will clarify them via call.
